# Generated by Django 5.2.12 on 2026-04-23 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('total_seats', models.PositiveIntegerField(default=100)),
                ('amenities', models.CharField(blank=True, help_text='Comma separated: Dolby, IMAX, etc.', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('release_date', models.DateField()),
                ('rating', models.CharField(choices=[('U', 'U - Universal'), ('UA', 'UA - Universal Adult'), ('A', 'A - Adults Only')], default='UA', max_length=5)),
                ('imdb_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('trailer_youtube_id', models.CharField(blank=True, help_text='YouTube video ID only', max_length=20)),
                ('is_now_showing', models.BooleanField(default=True)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
                ('languages', models.ManyToManyField(related_name='movies', to='movies.language')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.DateTimeField()),
                ('price_regular', models.DecimalField(decimal_places=2, default=150.0, max_digits=8)),
                ('price_premium', models.DecimalField(decimal_places=2, default=250.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.language')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.theater')),
            ],
            options={
                'ordering': ['show_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('regular', 'Regular'), ('premium', 'Premium'), ('recliner', 'Recliner')], default='regular', max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_held', models.BooleanField(default=False)),
                ('held_until', models.DateTimeField(blank=True, null=True)),
                ('held_by_session', models.CharField(blank=True, max_length=100)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.show')),
            ],
            options={
                'unique_together': {('show', 'seat_number')},
            },
        ),
    ]
