# Generated by Django 5.1.3 on 2026-04-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='song_teaser_youtube_id',
            field=models.CharField(blank=True, help_text='Fallback teaser video ID', max_length=20),
        ),
    ]
