# Generated by Django 6.0.4 on 2026-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_song_teaser_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Full trailer URL (YouTube watch or embed URL)', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_youtube_id',
            field=models.CharField(blank=True, help_text='YouTube video ID only', max_length=50),
        ),
    ]
