# Generated by Django 6.0.4 on 2026-06-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_trailer_url_alter_movie_trailer_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, help_text='Remote poster image URL', max_length=500, null=True),
        ),
    ]
